name: CI

on:
  push:
    branches: [ main ]
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # Install all dependencies (server + client)
      - name: Install dependencies
        run: npm ci

      # Typecheck
      - name: Typecheck
        run: npx tsc --noEmit || echo "Skipping typecheck if no tsconfig"

      # Build application
      - name: Build
        run: npm run build

      # Upload build as artifact (handy for debugging)
      - name: Upload build
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

      # OPTIONAL: publish a Sentry release & upload source maps (only if secrets configured)
      - name: Create Sentry release (web)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && secrets.SENTRY_AUTH_TOKEN != ''
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT_WEB }}
          RELEASE: ${{ github.sha }}
        run: |
          npx @sentry/cli releases new "$RELEASE"
          npx @sentry/cli releases set-commits "$RELEASE" --auto
          npx @sentry/cli releases files "$RELEASE" upload-sourcemaps dist --url-prefix '~/'
          npx @sentry/cli releases finalize "$RELEASE"

  e2e-ping:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: Ping healthz
        env:
          PROD_SITE_URL: ${{ secrets.PROD_SITE_URL }}
        run: |
          set -euo pipefail
          curl -fsSL "$PROD_SITE_URL/api/healthz"
          echo "OK"